In [2]:
# Um programa simples que diz 'Hello Python World!'
print('Hello Python World!')

Hello Python World!

In [3]:
'''
    2) Cálculos com NumPy: Selecione uma coluna numérica e utilize o NumPy para calcular manualmente a média, mediana e o desvio padrão. Compare com o resultado do .describe() do Pandas.
'''

'\n    2) Cálculos com NumPy: Selecione uma coluna numérica e utilize o NumPy para calcular manualmente a média, mediana e o desvio padrão. Compare com o resultado do .describe() do Pandas.\n'

In [5]:
# Importando as ferramentas que serão usadas
import seaborn as sns
import pandas as pd
import numpy as np

# Carregando um dataset interno do Seaborn
df = sns.load_dataset('car_crashes')

# Mostra as 5 primeiras linhas do dataset 'car_crashes'
df.head()

,total,speeding,alcohol,not_distracted,no_previous,ins_premium,ins_losses,abbrev
0,18.8,7.332,5.640,18.048,15.040,784.55,145.08,AL
1,18.1,7.421,4.525,16.290,17.014,1053.48,133.93,AK
2,18.6,6.510,5.208,15.624,17.856,899.47,110.35,AZ
3,22.4,4.032,5.824,21.056,21.280,827.34,142.39,AR
4,12.0,4.200,3.360,10.920,10.680,878.41,165.63,CA

In [8]:
coluna_total = df.total # Número de motoristas envolvidos em acidentes fatais por bilhão de milhas percorridas.

# Mostra a coluna selecionada
print(coluna_total)

0     18.8
1     18.1
2     18.6
3     22.4
4     12.0
5     13.6
6     10.8
7     16.2
8      5.9
9     17.9
10    15.6
11    17.5
12    15.3
13    12.8
14    14.5
15    15.7
16    17.8
17    21.4
18    20.5
19    15.1
20    12.5
21     8.2
22    14.1
23     9.6
24    17.6
25    16.1
26    21.4
27    14.9
28    14.7
29    11.6
30    11.2
31    18.4
32    12.3
33    16.8
34    23.9
35    14.1
36    19.9
37    12.8
38    18.2
39    11.1
40    23.9
41    19.4
42    19.5
43    19.4
44    11.3
45    13.6
46    12.7
47    10.6
48    23.8
49    13.8
50    17.4
Name: total, dtype: float64

In [12]:
# Soma os valores númericos da coluna com numpy
soma = np.sum(coluna_total)

# Conta a quantidade de itens usando len()
quantidade = len(coluna_total)

# Cálculo da média manualmente
media = soma / quantidade

# Imprime a média com 2 (Duas) casas decimais
print(f"\nA média é = {media:.2f}")

A média é = 15.79

In [15]:
# Cálculo da Mediana com numpy
mediana = np.median(coluna_total)

# Imprime a mediana com 2 (Duas) casas decimais
print(f"\nA mediana é = {mediana:.2f}")

A mediana é = 15.60

In [19]:
# Cálculo do Desvio Padrão com numpy
desvio_padrao = np.std(coluna_total)

# Desvio Padrão Amostral
desvio_amost = np.std(coluna_total, ddof=1)

print(f"\nDesvio Padrão = {desvio_padrao}")
print(f"\nDesvio Padrão Amostral = {desvio_amost}")

Desvio Padrão = 4.081390329333471

Desvio Padrão Amostral = 4.122002178648661

In [20]:
df.describe()

,total,speeding,alcohol,not_distracted,no_previous,ins_premium,ins_losses
count,51.000000,51.000000,51.000000,51.000000,51.000000,51.000000,51.000000
mean,15.790196,4.998196,4.886784,13.573176,14.004882,886.957647,134.493137
std,4.122002,2.017747,1.729133,4.508977,3.764672,178.296285,24.835922
min,5.900000,1.792000,1.593000,1.760000,5.900000,641.960000,82.750000
25%,12.750000,3.766500,3.894000,10.478000,11.348000,768.430000,114.645000
50%,15.600000,4.608000,4.554000,13.857000,13.775000,858.970000,136.050000
75%,18.500000,6.439000,5.604000,16.140000,16.755000,1007.945000,151.870000
max,23.900000,9.450000,10.038000,23.661000,21.280000,1301.520000,194.780000